.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. maza_qt test_maza_qt
clean: FORCE
	$(MAKE) -C .. maza_qt_clean test_maza_qt_clean
check: FORCE
	$(MAKE) -C .. test_maza_qt_check
maza-qt maza-qt.exe: FORCE
	 $(MAKE) -C .. maza_qt
